Fixing for Android 12 (#123)
* Fixing for Android 12

java.lang.RuntimeException: Unable to create service com.google.flutter.plugins.audiofileplayer.AudiofileplayerService: java.lang.IllegalArgumentException: com.layamritam.app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

* Update AudiofileplayerService.java

* Upgraded media library dependancy to 1.3.0

* Removing the unused exception